INSERT INTO tb_autor (id, nome-autor) VALUES ('1','ADRIANO DIOGO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('2','ANTONIO SAMPAIO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('3','GABRIEL ORTEGA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('4','EXECUTIVO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('5','LUIZA ERUNDINA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('6','TEREZA CRISTINA DE SOUZA LAJOLO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('7','ITALO CARDOSO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('8','BRUNO FEDER');
INSERT INTO tb_autor (id, nome-autor) VALUES ('9','USHITARO KAMIA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('10','EDSON FALANGA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('11','MARIO NODA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('12','OSVALDO GIANNOTTI');
INSERT INTO tb_autor (id, nome-autor) VALUES ('13','AURELINO DE ANDRADE');
INSERT INTO tb_autor (id, nome-autor) VALUES ('14','MARCOS MENDONCA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('15','ANDRADE FIGUEIRA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('16','PAULO KOBAYASHI');
INSERT INTO tb_autor (id, nome-autor) VALUES ('17','ALFREDO MARTINS');
INSERT INTO tb_autor (id, nome-autor) VALUES ('18','BRASIL VITA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('19','PAULO MALUF');
INSERT INTO tb_autor (id, nome-autor) VALUES ('20','GILBERTO KASSAB');
INSERT INTO tb_autor (id, nome-autor) VALUES ('21','TONINHO PAIVA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('22','ALMIR GUIMARAES');
INSERT INTO tb_autor (id, nome-autor) VALUES ('23','EMILIO MENEGHINI');
INSERT INTO tb_autor (id, nome-autor) VALUES ('24','JOSE VIVIANI FERRAZ');
INSERT INTO tb_autor (id, nome-autor) VALUES ('25','ARCHIBALDO ZANCRA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('26','NELO RODOLFO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('27','DALMO PESSOA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('28','OSVALDO SANCHES');
INSERT INTO tb_autor (id, nome-autor) VALUES ('29','COSME LOPES');
INSERT INTO tb_autor (id, nome-autor) VALUES ('30','MARIO DIAS');
INSERT INTO tb_autor (id, nome-autor) VALUES ('31','ALEX FREUA NETO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('32','ARNALDO MADEIRA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('33','WADIH MUTRAN');
INSERT INTO tb_autor (id, nome-autor) VALUES ('34','ALBERTO CALVO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('35','EDIVALDO ESTIMA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('36','HENRIQUE PACHECO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('37','MIGUEL COLASUONNO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('38','ANTONIO CARLOS CARUSO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('39','HANNA GHARIB');
INSERT INTO tb_autor (id, nome-autor) VALUES ('40','VICENTE VISCOME');
INSERT INTO tb_autor (id, nome-autor) VALUES ('41','DARCIO ARRUDA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('42','ARSELINO TATTO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('43','ZENAS PIRES');
INSERT INTO tb_autor (id, nome-autor) VALUES ('44','MANOEL SALA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('45','PAULO ROBERTO FARIA LIMA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('46','MOHAMAD SAID MOURAD');
INSERT INTO tb_autor (id, nome-autor) VALUES ('47','NELSON GUIMARAES PROENCA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('48','AURELIO NOMURA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('49','LIDIA CORREA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('50','JOOJI HATO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('51','GILSON BARRETO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('52','ALBERTO HIAR');
INSERT INTO tb_autor (id, nome-autor) VALUES ('53','JOSE INDIO FERREIRA DO NASCIMENTO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('54','AVANIR DURAN GALHARDO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('55','MARCOS CINTRA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('56','EDSON SIMOES');
INSERT INTO tb_autor (id, nome-autor) VALUES ('57','NELSON GUERRA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('58','JOSE SILVA AMORIM');
INSERT INTO tb_autor (id, nome-autor) VALUES ('59','LUIZ PASCHOAL');
INSERT INTO tb_autor (id, nome-autor) VALUES ('60','IVO MORGANTI');
INSERT INTO tb_autor (id, nome-autor) VALUES ('61','CARLOS NEDER');
INSERT INTO tb_autor (id, nome-autor) VALUES ('62','CELSO PITTA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('63','PAULO FRANGE');
INSERT INTO tb_autor (id, nome-autor) VALUES ('64','JOSE MENTOR');
INSERT INTO tb_autor (id, nome-autor) VALUES ('65','PIERRE ALEXANDRE DE FREITAS');
INSERT INTO tb_autor (id, nome-autor) VALUES ('66','DITO SALIM');
INSERT INTO tb_autor (id, nome-autor) VALUES ('67','DOMINGOS DISSEI');
INSERT INTO tb_autor (id, nome-autor) VALUES ('68','JORGE TABA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('69','GOULART');
INSERT INTO tb_autor (id, nome-autor) VALUES ('70','MARIA HELENA PEREIRA FONTES');
INSERT INTO tb_autor (id, nome-autor) VALUES ('71','OSVALDO ENEAS');
INSERT INTO tb_autor (id, nome-autor) VALUES ('72','CELSO CARDOSO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('73','ARMANDO MELLAO NETO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('74','MAELI VERGNIANO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('75','JOSE IZAR');
INSERT INTO tb_autor (id, nome-autor) VALUES ('76','DALTON SILVANO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('77','SALIM CURIATI');
INSERT INTO tb_autor (id, nome-autor) VALUES ('78','ANA MARIA QUADROS');
INSERT INTO tb_autor (id, nome-autor) VALUES ('79','CARLOS ZARATTINI');
INSERT INTO tb_autor (id, nome-autor) VALUES ('80','VICENTE CANDIDO DA SILVA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('81','NATALICIO BEZERRA SILVA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('82','JOSE OLIMPIO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('83','MILTON LEITE');
INSERT INTO tb_autor (id, nome-autor) VALUES ('84','ALAN LOPES');
INSERT INTO tb_autor (id, nome-autor) VALUES ('85','CARLOS GIANNAZI');
INSERT INTO tb_autor (id, nome-autor) VALUES ('86','ANTONIO CARLOS RODRIGUES');
INSERT INTO tb_autor (id, nome-autor) VALUES ('87','TONINHO CAMPANHA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('88','MARTA SUPLICY');
INSERT INTO tb_autor (id, nome-autor) VALUES ('89','NATALINI');
INSERT INTO tb_autor (id, nome-autor) VALUES ('90','MYRYAM ATHIE');
INSERT INTO tb_autor (id, nome-autor) VALUES ('91','WILLIAM WOO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('92','RUBENS CALVO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('93','ANA MARTINS');
INSERT INTO tb_autor (id, nome-autor) VALUES ('94','JOSE LAURINDO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('95','BETO CUSTODIO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('96','ELISEU GABRIEL');
INSERT INTO tb_autor (id, nome-autor) VALUES ('97','CELSO JATENE');
INSERT INTO tb_autor (id, nome-autor) VALUES ('98','ERASMO DIAS');
INSERT INTO tb_autor (id, nome-autor) VALUES ('99','JOAO ANTONIO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('100','ROBERTO TRIPOLI');
INSERT INTO tb_autor (id, nome-autor) VALUES ('101','AUGUSTO CAMPOS');
INSERT INTO tb_autor (id, nome-autor) VALUES ('102','FLAVIA PEREIRA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('103','LUCILA PIZANI GONCALVES');
INSERT INTO tb_autor (id, nome-autor) VALUES ('104','VANDERLEI JANGROSSI');
INSERT INTO tb_autor (id, nome-autor) VALUES ('105','JOSE EDUARDO CARDOZO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('106','CLAUDETE ALVES');
INSERT INTO tb_autor (id, nome-autor) VALUES ('107','RICARDO MONTORO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('108','TITA DIAS');
INSERT INTO tb_autor (id, nome-autor) VALUES ('109','RAUL CORTEZ');
INSERT INTO tb_autor (id, nome-autor) VALUES ('110','MANOEL CRUZ');
INSERT INTO tb_autor (id, nome-autor) VALUES ('111','CARLOS ALBERTO BEZERRA JR.');
INSERT INTO tb_autor (id, nome-autor) VALUES ('112','FRANCISCO CHAGAS');
INSERT INTO tb_autor (id, nome-autor) VALUES ('113','ZELIA LOPES - D ZELIA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('114','JOSE NOGUEIRA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('115','JOSE AMERICO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('116','JOSE FERREIRA (ZELAO)');
INSERT INTO tb_autor (id, nome-autor) VALUES ('117','CLAUDIO FONSECA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('118','CLAUDINHO DE SOUZA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('119','ABOU ANNI');
INSERT INTO tb_autor (id, nome-autor) VALUES ('120','PAULO TEIXEIRA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('121','ATTILA RUSSOMANNO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('122','ADOLFO QUINTAS');
INSERT INTO tb_autor (id, nome-autor) VALUES ('123','LENICE LEMOS');
INSERT INTO tb_autor (id, nome-autor) VALUES ('124','ADEMIR DA GUIA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('125','ADILSON AMADEU');
INSERT INTO tb_autor (id, nome-autor) VALUES ('126','AGNALDO TIMOTEO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('127','ATILIO FRANCISCO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('128','AURELIO MIGUEL');
INSERT INTO tb_autor (id, nome-autor) VALUES ('129','NOEMI NONATO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('130','JOSE SERRA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('131','MARTA COSTA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('132','JUSCELINO GADELHA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('133','FARHAT');
INSERT INTO tb_autor (id, nome-autor) VALUES ('134','DONATO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('135','SENIVAL MOURA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('136','MARCOS ZERBINI');
INSERT INTO tb_autor (id, nome-autor) VALUES ('137','SONINHA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('138','CHICO MACENA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('139','CLAUDIO PRADO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('140','PAULO FIORILO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('141','JOSE ROLIM');
INSERT INTO tb_autor (id, nome-autor) VALUES ('142','RICARDO TEIXEIRA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('143','MARA GABRILLI');
INSERT INTO tb_autor (id, nome-autor) VALUES ('144','FLORIANO PESARO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('145','JOSE POLICE NETO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('146','MARCELO AGUIAR');
INSERT INTO tb_autor (id, nome-autor) VALUES ('147','CARLOS APOLINARIO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('148','JAMIL MURAD');
INSERT INTO tb_autor (id, nome-autor) VALUES ('149','PENNA');
INSERT INTO tb_autor (id, nome-autor) VALUES ('150','EDIR SALES');
INSERT INTO tb_autor (id, nome-autor) VALUES ('151','ALFREDO CAVALCANTE');
INSERT INTO tb_autor (id, nome-autor) VALUES ('152','JULIANA CARDOSO');
INSERT INTO tb_autor (id, nome-autor) VALUES ('153','SANDRA TADEU');
INSERT INTO tb_autor (id, nome-autor) VALUES ('154','MESA DA CAMARA MUNICIPAL DE SAO PAULO');

